version: "3"
services:
  react:
    build: .
    volumes:
      - ./app:/usr/src/app
    ports:
      - 3000:3000
    working_dir: /usr/src/app
    command: ['yarn', 'start']
  server:
    build: .
    volumes:
      - ./server:/usr/src/app
    ports:
      - 4000:4000
    working_dir: /usr/src/app
    command: ['yarn', 'start']
